/* Ideias de temas em alta para as caixas, para a aba Temas do painel.
   BASE: pesquisa de tendências de papelaria feita em 2026 (não é uma busca ao vivo do Google, e sim um resumo do que
   aparece nas pesquisas e matérias do setor). Atualizar de tempos em tempos.
   Cada ideia já vem com descrição e produtos na MESMA forma de escrita das donas (veja ThemeArt.compose). */
const THEME_IDEAS = (function () {
  const C = ThemeArt.compose, D = ThemeArt.dash, P = ThemeArt.PURPOSES;
  let n = 0; // a frase "Tudo pensado para..." alterna entre as 3 variações das donas, sempre na mesma ordem
  const idea = (title, why, season, x) => ({ title, why, season, description: C({ ...x, purpose: x.purpose || P[n++ % P.length] }), products: D(x.products) });
  return [
    idea("🦫Capivara Zen🦫", "A capivara virou símbolo de calma e de fofura nas redes e na papelaria brasileira.", "O ano todo", { hook: "Respira fundo: hoje o ritmo é o da capivara.", elements: "capivaras, águas calmas, folhas e muito bem-estar", emojis: "🦫🌿", products: ["Caderneta com a capivara", "Adesivos de capivara e folhas", "Canetas em tons de verde", "Marca-textos suaves", "Washi tape de plantinhas", "Cartão com frase zen"] }),
    idea("🐰Bichinhos Kawaii🐰", "O estilo kawaii segue forte entre estudantes e jovens adultos.", "O ano todo", { hook: "Um mundinho de bichinhos que só sabem espalhar fofura.", elements: "coelhinhos, ursinhos, gatinhos e carinhas sorridentes", emojis: "🐰💕", products: ["Caderneta kawaii", "Adesivos de bichinhos", "Canetas coloridas", "Marca-textos pastel", "Post-its de carinhas", "Cartão com recado fofo"] }),
    idea("🎀Laço e Coquette🎀", "A estética coquette (laços, renda e rosa-claro) é muito procurada.", "O ano todo", { hook: "Delicadeza em cada detalhe, com laço e tudo.", elements: "laços, renda, pérolas e tons de rosa e creme", emojis: "🎀🤍", products: ["Caderneta com laço", "Adesivos de laços e pérolas", "Canetas rosa e creme", "Marca-textos suaves", "Washi tape rendada", "Cartão com recado romântico"] }),
    idea("📚Dark Academia📚", "Estética de biblioteca e livros antigos em alta entre universitários.", "Volta às aulas", { hook: "Para quem ama o cheiro de livro e o silêncio da biblioteca.", elements: "livros antigos, velas, tons terrosos e caligrafia clássica", emojis: "📚🕯️", products: ["Caderno de capa vintage", "Adesivos de livros e velas", "Caneta com tinta escura", "Marca-páginas", "Washi tape clássica", "Cartão com citação literária"] }),
    idea("🌿Cantinho no Campo🌿", "Cottagecore e temas botânicos seguem entre os favoritos dos diários.", "Primavera", { hook: "Uma tarde tranquila numa casinha cheia de plantas.", elements: "ervas, florzinhas do campo, cestas e luz de fim de tarde", emojis: "🌿🧺", products: ["Caderneta botânica", "Adesivos de flores do campo", "Canetas em tons verdes", "Marca-textos pastel", "Washi tape florzinha", "Cartão com mensagem acolhedora"] }),
    idea("🍓Piquenique de Frutas🍓", "Cores vivas e frutinhas combinam com o estilo \"dopamina\" que está em alta.", "Verão", { hook: "Um piquenique inteiro cabendo no seu caderno.", elements: "morangos, cerejas, limões e cores bem vivas", emojis: "🍓🍋", products: ["Caderneta de frutinhas", "Adesivos de frutas", "Canetas coloridas", "Marca-textos vibrantes", "Washi tape xadrez", "Cartão com recado alegre"] }),
    idea("🌈Dopamina Colorida🌈", "O \"maximalismo da dopamina\" (muita cor e alegria) é tendência de 2026.", "O ano todo", { hook: "Cor demais nunca é demais.", elements: "arco-íris, cores vibrantes, formas divertidas e muito bom humor", emojis: "🌈⚡", products: ["Caderneta multicolorida", "Adesivos vibrantes", "Conjunto de canetas coloridas", "Marca-textos neon suaves", "Washi tape colorida", "Cartão com mensagem animada"] }),
    idea("☕Café e Livros☕", "Clima aconchegante de leitura e planner é muito buscado.", "Outono e inverno", { hook: "Uma xícara quentinha e um caderno aberto.", elements: "café, livros, mantinhas e tons quentes", emojis: "☕📖", products: ["Caderneta tema café", "Adesivos de xícaras e livros", "Canetas em tons de caramelo", "Marca-textos suaves", "Washi tape listrada", "Cartão com recado acolhedor"] }),
    idea("🎃Doce ou Travessura🎃", "Halloween fofo (sem susto) vende muito em outubro.", "Outubro", { hook: "Aqui o susto é só de fofura.", elements: "abóboras, fantasminhas, morcegos e doces", emojis: "🎃👻", products: ["Caderneta de abóbora", "Adesivos de fantasminhas", "Canetas laranja e roxa", "Marca-textos pastel", "Washi tape de morcegos", "Cartão com recado travesso"] }),
    idea("🎄Natal Encantado🎄", "O fim de ano é a época de maior procura por presentes de papelaria.", "Novembro e dezembro", { hook: "A magia do Natal chegando na sua mesa de estudos.", elements: "pinheiros, neve, luzinhas e pequenos presentes", emojis: "🎄✨", products: ["Caderneta de fim de ano", "Adesivos natalinos", "Canetas vermelhas e verdes", "Marca-textos pastel", "Washi tape festivo", "Cartão para presentear"] }),
    idea("🏖️Verão no Papel🏖️", "Férias e praia puxam a procura por cores leves e tropicais.", "Dezembro a fevereiro", { hook: "Sol, brisa e um caderno para guardar as férias.", elements: "ondas, conchas, sorvetes e cores tropicais", emojis: "🌊☀️", products: ["Bloquinho de praia", "Adesivos de conchas e sorvetes", "Canetas em tons tropicais", "Marca-textos coloridos", "Washi tape ondas", "Cartão com mensagem de verão"] }),
    idea("🎒Volta às Aulas Fofa🎒", "Janeiro e fevereiro são os meses em que a papelaria mais vende no Brasil.", "Janeiro e fevereiro", { hook: "Começar o ano com tudo organizado (e muito fofo).", elements: "cadernos, planners, estojos e adesivos de organização", emojis: "🎒✏️", products: ["Planner ou caderno de estudos", "Adesivos de organização", "Canetas coloridas", "Marca-textos", "Post-its decorados", "Marcador de páginas"] }),
    idea("🧸Nostalgia dos Anos 90🧸", "Retrô e nostalgia continuam fortes em cadernos e adesivos.", "O ano todo", { hook: "Uma viagem no tempo de volta à infância.", elements: "bichinhos de pelúcia, fitas coloridas, estrelas e cores dos anos 90", emojis: "🧸📼", products: ["Caderneta retrô", "Adesivos nostálgicos", "Canetas gel coloridas", "Marca-textos", "Washi tape retrô", "Cartão com recado antigo"] }),
    idea("🌊Mar de Sonhos🌊", "Tons de azul-mar e verde-água estão entre as paletas da temporada.", "Verão", { hook: "O azul do mar deixa qualquer pensamento mais leve.", elements: "ondas, conchas, estrelas-do-mar e tons de azul e verde-água", emojis: "🌊🐚", products: ["Caderneta azul-mar", "Adesivos de conchas e peixinhos", "Canetas em tons de mar", "Marca-textos pastel", "Washi tape ondas", "Cartão com mensagem serena"] }),
    idea("🤍Minimalismo Soft🤍", "Papelaria clean, no estilo coreano, segue forte nos diários.", "O ano todo", { hook: "Menos é mais, e tudo no lugar certo.", elements: "tons neutros, linhas delicadas e muito respiro", emojis: "🤍☁️", products: ["Caderneta lisa em tons neutros", "Adesivos minimalistas", "Canetas finas", "Marca-textos suaves", "Washi tape discreta", "Cartão com frase curta"] }),
    idea("🐱Gatinhos Preguiçosos🐱", "Bichinhos sonolentos e fofos aparecem muito nas buscas por papelaria.", "O ano todo", { hook: "Todo dia merece uma sonequinha de gatinho.", elements: "gatinhos, almofadas, lã e cores quentinhas", emojis: "🐱💤", products: ["Caderneta de gatinhos", "Adesivos de gatinhos", "Canetas em tons pastel", "Marca-textos", "Post-its de patinhas", "Cartão com recado miau"] }),
    idea("🪄Magia e Poções🪄", "Temas de bruxinha fofa e fantasia agradam o público jovem.", "O ano todo", { hook: "Um feitiço de criatividade para cada página.", elements: "varinhas, poções, estrelas e livros de magia", emojis: "🪄🔮", products: ["Caderneta de feitiços", "Adesivos de poções e estrelas", "Canetas com brilho", "Marca-textos pastel", "Washi tape mágica", "Cartão com um feitiço do dia"] }),
    idea("💐Flores para a Mamãe💐", "O Dia das Mães é uma das datas que mais vendem presentes de papelaria.", "Maio", { hook: "Para dar (ou ganhar) com muito carinho.", elements: "flores, laços, corações e mensagens de amor", emojis: "💐💕", products: ["Caderneta floral", "Adesivos de flores e corações", "Canetas em tons de rosa", "Marca-textos suaves", "Washi tape delicada", "Cartão para escrever uma declaração"] }),
    idea("💌Cartas de Amor💌", "O Dia dos Namorados (12 de junho) pede presentes pequenos e afetivos.", "Junho", { hook: "Escrever à mão ainda é o jeito mais bonito de dizer eu te amo.", elements: "cartas, envelopes, selos e corações", emojis: "💌💗", products: ["Caderneta de cartas", "Adesivos de envelopes e corações", "Canetas em tons de rosa e vinho", "Marca-textos pastel", "Washi tape de corações", "Cartões para escrever"] }),
    idea("🎉Arraiá Fofo🎉", "A Festa Junina rende temas coloridos e muito brasileiros.", "Junho e julho", { hook: "Bandeirinhas, fogueira e muito quentão de fofura.", elements: "bandeirinhas, milho, xadrez e balõezinhos", emojis: "🎉🌽", products: ["Caderneta xadrez", "Adesivos de bandeirinhas", "Canetas coloridas", "Marca-textos", "Washi tape de bandeirinhas", "Cartão de convite junino"] }),
  ];
})();
